### ISSUE TITLE
Cloning Issue (CA-83)

### ISSUE THREAD

**Issue by intothefuture20** [espressif/esp-azure#101]
While cloning got the following errors:

Failed to recurse into submodule path 'azure-iot-sdk-c/provisioning_client/deps/utpm'
Failed to recurse into submodule path 'azure-iot-sdk-c/uamqp'
Failed to recurse into submodule path 'azure-iot-sdk-c'

![image](https://user-images.githubusercontent.com/36773209/90493404-f3ffed00-e15f-11ea-9447-69615ba86c1c.png)

Seeking assistance please.

**Comment by shahpiyushv** [comment]
@intothefuture20 I think just trying again should resolve this issue. ESP Azure just has a single sub-module azure-iot-sdk-c, but azure-iot-sdk-c itself has many more sub-modules.

**Comment by intothefuture20** [comment]
Hello Piyush, I tried again and its same result... Same Error

**Comment by shahpiyushv** [comment]
@intothefuture20 , that is strange. I just tried recursive cloning using command line as well as github desktop app. Both worked fine. Seems there could be some network issue on your side?

If the parent esp-azure repo has been cloned already, can you just try fetching the submodules a few more times using the below from esp-azure folder?

```
git submodule update --init --recursive
```

**Comment by zafarpatel7** [comment]
HI @intothefuture20 
if your c/d driver path is long it will not work - so direct Clone at C: or D: (D:\esp-azure) then it will work

**Comment by intothefuture20** [comment]
Hello Zafar,

Well it did work when I cloned it on root like c drive or D drive. Thank you all for the help. Much Appreciated!

**Comment by intothefuture20** [comment]
The issue is resolved. Closing the issue. Thank you!
