### ISSUE TITLE
not finding macro_utils.h (CA-93)

### ISSUE THREAD

**Issue by besso-exceline** [espressif/esp-azure#104]
I have updated my project to idf version 4.1 and it is now not able to find path to
azure_c_shared_utility/macro_utils.h

fatal error: azure_c_shared_utility/macro_utils.h: No such file or directory
 #include "azure_c_shared_utility/macro_utils.h"

**Comment by besso-exceline** [comment]
I see you changed names ENUM_TO_STRING to MU_ENUM_TO_STRING :(

**Comment by shahpiyushv** [comment]
> I see you changed names ENUM_TO_STRING to MU_ENUM_TO_STRING :(

This change actually came from the underlying azure-iot-sdk-c as we moved to a newer LTS release.
