### ISSUE TITLE
how can we come out of azure function

### ISSUE THREAD

**Issue by naznaaa** [espressif/esp-azure#29]
Hi,

we have to send some messages to azure iot ,after that we have to come out of this functon to do some other action
we use the sample https://github.com/espressif/esp-azure/tree/master/examples/iothub_client_sample_mqtt 
here after sending messages and recieving confirmation we have to do some other function, but here it's going with ->pingreq and ->pingresp 
how can we come out of this fuction can you please help

**Comment by jitin17** [comment]
@naznaaa `SendConfirmationCallback ` is the confirmation callback function in this  https://github.com/espressif/esp-azure/tree/master/examples/iothub_client_sample_mqtt example. So, invoke the function you want to call after receiving confirmation in `SendConfirmationCallback` function.

**Comment by mahavirj** [comment]
Closing, assuming above answers the question. Please feel free to reopen if there is any issue.
