### ISSUE TITLE
Is there anyway I can use azure in esp32 using arduino framewrok?

### ISSUE THREAD

**Issue by Praveena0989** [espressif/esp-azure#4]
Thanks for the wonderful work. I use esp32 and Arduino framework together. How can  I use Azure in that combination?

**Comment by ustccw** [comment]
@Praveena0989 Sorry, we did not try this azure SDK in Arduino framework. 
and this SDK supports both ESP32 platform with [esp-idf](https://github.com/espressif/esp-idf) and ESP8266 platform with [ESP8266_RTOS_SDK](https://github.com/espressif/ESP8266_RTOS_SDK).
