### ISSUE TITLE
az iot hub: 'monitor-events' is not in the 'az iot hub' command group. See 'az iot hub --help'.

### ISSUE THREAD

**Issue by pelikhan** [espressif/esp-azure#41]
The command in the readme does not work with the latest az cli (2.0.67)

```
>az iot hub monitor-events -n "..." -login "..."
az iot hub: 'monitor-events' is not in the 'az iot hub' command group. See 'az iot hub --help'.
```

**Comment by shahpiyushv** [comment]
@pelikhan , please execute `az extension add --name azure-cli-iot-ext` once and try again.

**Comment by pelikhan** [comment]
It went a bit further but now it complains that the connection string I got from the Azure portal is missing SharedAccessKeyName.

```
IoT Hub connection string has missing property: SharedAccessKeyName
```

**Comment by shahpiyushv** [comment]
@pelikhan , for which command did you get this error? Once you login using az login, for monitoring the events, `az iot hub monitor-events -n <Hub name>` should be sufficient. We will correct the steps accordingly.

**Comment by pelikhan** [comment]
Dropping the token in the ``monitor-events`` invocation worked. thanks.

**Comment by shahpiyushv** [comment]
@pelikhan , I am closing this issue as it has been resolved. We have also updated the documentation so that trying out the examples is easy.
