### ISSUE TITLE
Support for current IDF

### ISSUE THREAD

**Issue by jubueche** [espressif/esp-azure#53]
Hi,

this library is really cool, but ESP is moving forward with their IDF version so it would be nice if we could use a newer IDF version. I tried it but it gave me a lot of compiling errors.

**Comment by chinmaychhajed** [comment]
We will be adding support of newer IDF versions, but currently all the testing has been done using [IDF release/v3.3](https://github.com/espressif/esp-idf/tree/release/v3.3). Please use this version and let us know if you still face any problems.

**Comment by NielsVeul** [comment]
Hi, do you have any idea on when support for IDF v4.0 will be added? And will the next release work with a newer version of the azure-iot-sdk-c?

**Comment by chinmaychhajed** [comment]
It is in plan but not yet a priority item, as IDF 4.0 will need some time to stabilise first. Whenever that happens, we will also ensure that the latest  azure-iot-sdk-c is used

**Comment by fromeijn** [comment]
would like to see this happen any time soon :wink:

**Comment by shahpiyushv** [comment]
@jubueche @fromeijn @NielsVeul , the esp_azure has been updated. It can now compile with IDF tag: v4.0-beta1

**Comment by jubueche** [comment]
Closing this. Any issues appearing would be separate ones.
