### ISSUE TITLE
#unable to connect esp32-azure using c sdk 

### ISSUE THREAD

**Issue by enerdata** [espressif/esp-azure#59]
Hi there,

iam working on esp32 azure ,unable to connect azure and the error is

 Func:tlsio_esp_tls_destroy Line:152 tlsio_esp_tls_destroy called while not in TLSIO_STATE_CLOSED.

**Comment by shahpiyushv** [comment]
@enerdata , which example are you using? We have updated some documentation right now. Can you try as per that documentation?

**Comment by enerdata** [comment]
yeah !!

i will try now 
Thank you @shahpiyushv

**Comment by enerdata** [comment]
Hi @shahpiyushv 
i cloned the updated git , but still iam facing the same issue can you please guide to resolve it ?

**Comment by shahpiyushv** [comment]
@enerdata , is this related to https://github.com/espressif/esp-azure/issues/66 ? which example are you using?

**Comment by enerdata** [comment]
Hi @shahpiyushv  ,
Greetings of the day!!!

i'am using this example iothub_client_sample_mqtt..

**Comment by enerdata** [comment]
![iothub_error](https://user-images.githubusercontent.com/53897445/68271285-1075e180-0086-11ea-9a47-47466edcd6c2.png)
please check that image ....... iam getting the above error..

**Comment by shahpiyushv** [comment]
@enerdata , does your issue seem somewhat similar to this: https://github.com/espressif/esp-idf/issues/3192? The fix for this is already available on the ESP IDF master branch now.

**Comment by enerdata** [comment]
Hi @shahpiyushv 

error resolved ...

Thank you!!!
