### ISSUE TITLE
How do we use the latest azure iot 1.3.8 to replace the embedded one in the board definition? (CA-50)

### ISSUE THREAD

**Issue by haligasd** [espressif/esp-azure#82]
the version in the board is 

#define IOTHUB_SDK_VERSION "1.1.23"

which given these version was sometime in 2017 

https://www.arduinolibraries.info/libraries/azure-io-t-hub

**Comment by shahpiyushv** [comment]
@haligasd , the azure-iot-c-sdk has now been updated to the latest (pre)release LTS_06_2020_Ref01 .

**Comment by shahpiyushv** [comment]
Closing this issue as it has been addressed.
