### ISSUE TITLE
build error: apps/sntp/sntp.h: No such file or directory

### ISSUE THREAD

**Issue by qt1** [espressif/esp-azure#9]
Tried:

    git clone https://github.com/espressif/esp-azure.git --recurse-submodules
    cd esp-azure
    make

got
    ... agenttime_esp.c:23:28: fatal error: apps/sntp/sntp.h: No such file or directory

My unsubstantiated guess is that `esp-azure` is out of sync with  `esp-odf`

**Comment by igrr** [comment]
The fix for this will be in ESP-IDF very soon.

**Comment by ustccw** [comment]
@qt1 would you mind change `esp-idf` to `release/v3.0` branch.

**Comment by qt1** [comment]
@ustccw
I am already synced with latest version and it is even working with  current arduino so chaging the branch will break that.

**Comment by mahavirj** [comment]
@qt1 Please help to check once again, issue is now fixed.
