### ISSUE TITLE
Build Error (CA-68)

### ISSUE THREAD

**Issue by syamkrishnan-ESL** [espressif/esp-azure#91]
[error.txt](https://github.com/espressif/esp-azure/files/4845123/error.txt)
 I have tried to clone esp-azure to esp-idf and build as shown in log file attached.And getting errors as explained in above discussions.Ica build examples in esp-idf folder without any issues.Any suggestions please

**Comment by shahpiyushv** [comment]
@syamkrishnan-ESL , are you able to compile other esp-idf examples?

**Comment by syamkrishnan-ESL** [comment]
Yes now Iam able to .I have installed esp-idf again by cloning from repo.I used tools installer to install esp-idf before,which failed to compile examples except hello world.Now it can compile esp-idf\esp-azure\examples\iothub_client_sample_mqtt too.
Thanks,
Syam

**Comment by shahpiyushv** [comment]
@syamkrishnan-ESL , that is good to know. Closing this issue then.
