### ISSUE TITLE
Will there be an ESP32-S2 Azure coming soon? (CA-69)

### ISSUE THREAD

**Issue by askpatrickw** [espressif/esp-azure#92]
Will there be an ESP32-S2 Azure coming soon?
Will it demonstrating using the Digitial Signature Peripheral for working with self-signed and Espressif signed boards?

**Comment by shahpiyushv** [comment]
@askpatrickw I have already tested all 3 examples with ESP32-S2 and they work fine.
I will check on the demo for Digital Signature Peripheral, but that may happen some time later.

**Comment by askpatrickw** [comment]
Thank you @shahpiyushv That's great to hear!

**Comment by askpatrickw** [comment]
I should be more specific, what I (and I assume others) would like to see is the use of the Digital Signature Peripheral for securely managing the Azure IoT x.509 certificates. It would to good to also attach some documentation on if Espressif can per-cert the chips. I see it is a service offered by Espressif, but specifics related to Azure Iot alongside the sample code would be awesome.

Thanks so much!

**Comment by askpatrickw** [comment]
@shahpiyushv  Are you aware of any issues in using these samples with IoT Central? Specifically you first need to connect with DPS as your hub is never known, then use the hub in the result.
