### ISSUE TITLE
Is it possible use AMQP instead MQTT ? (CA-74)

### ISSUE THREAD

**Issue by sfarras** [espressif/esp-azure#95]
Is it possible use AMQP instead MQTT ?
Any example of that ?
I can't compile if I call  IoTHubClient_LL_CreateFromConnectionString(connectionString, **AMQP_Protocol**);

**Comment by SeriousD** [comment]
Same question I asked a few month ago.
Look here: #52

**Comment by sfarras** [comment]
I'm sorry, I didn't see that.
Thank you.
